# Generated by Django 4.2.1 on 2023-05-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('songs', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='playlist_covers')),
                ('description', models.TextField()),
                ('songs_id', models.ManyToManyField(related_name='playlists', to='songs.song')),
            ],
        ),
    ]
