# Generated by Django 4.2.1 on 2023-05-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='album',
            field=models.ManyToManyField(related_name='genres', to='songs.album'),
        ),
    ]
