# Generated by Django 4.2.1 on 2023-05-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_alter_album_cover_photo_alter_artist_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.ImageField(upload_to='songs'),
        ),
    ]
