# Generated by Django 4.2.1 on 2023-05-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_genre_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist_id',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.AddField(
            model_name='album',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/album_covers/'),
        ),
        migrations.AddField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/artist_photos/'),
        ),
    ]
