# Generated by Django 4.2.1 on 2023-05-26 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_remove_song_cover_song'),
        ('songs', '0003_alter_song_audio_file'),
    ]

    operations = [
    ]
