# Generated by Django 4.2.1 on 2023-05-31 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_alter_artist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='user',
        ),
    ]
