# Generated by Django 4.2.1 on 2023-05-25 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_rename_artist_id_album_artist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='album',
        ),
    ]
