# Generated by Django 4.2.1 on 2023-05-24 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('albums', models.CharField(max_length=200)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('release', models.DateField(auto_now_add=True)),
                ('genre', models.CharField()),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='main.artist')),
            ],
        ),
        migrations.CreateModel(
            name='SongFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.FileField(blank=True, null=True, upload_to='songs')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='main.track')),
            ],
        ),
    ]
